services:
  postgres:
    image: postgres:15
    ports:
      - "5678:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=money
      - POSTGRES_USER=broke_dev
      - POSTGRES_PASSWORD=broke

volumes:
  pgdata:
